SET SERVEROUTPUT ON
DECLARE
    NOMBRE VARCHAR2(20);
    numero INTEGER;
BEGIN
    SELECT REGION_NAME, REGION_ID INTO NOMBRE, NUMERO FROM REGIONS WHERE REGION_ID = 3;
    DBMS_OUTPUT.PUT_LINE('NOMBRE: ' ||NOMBRE|| ' Y SU NUMERO ES ' ||numero);
END;